### ISSUE TITLE
404 - not found

### ISSUE THREAD

**Issue by laurentopia** [fiftytwo/MailChimpSubscriber#1]
API key is fine, email as well and the list ID is set and the url seems well formed **https://us6.api.mailchimp.com/3.0/lists/cc498db04b/members**
```
MailChimp — Subscribe error 404: HTTP/1.1 404 Not Found
{"type":"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/","title":"Resource Not Found","status":404,"detail":"The requested resource could not be found.","instance":"..."}
UnityEngine.Debug:LogErrorFormat(String, Object[])
```

**Comment by laurentopia** [comment]
it needed a push, now it's working
note: if you get a 400, it's likely that you deleted a contact then re-entered it. I did that to test and mailchimp barked at me.

**Comment by mshagin** [comment]
Oh, yes, re-entering the same contact leads to an error state. Thanks for your comment on this, as I couldn't find what's the reason for this issue :)
